# Configuration options for dependabot
version: 2
updates:
  - package-ecosystem: "javascript"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include:
        - "Mightybeast12/portfolio_site"
    ignore:
      - dependency-name: "example-package"
        versions:
          - "<3.0.0"
        reason: "Stay on the same version for stability"